# Import the required libraries

In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Import the dataset

In [9]:
dataset = pd.read_csv("ai_job_market.csv")

In [11]:
dataset.head()

,job_id,company_name,industry,job_title,skills_required,experience_level,employment_type,location,salary_range_usd,posted_date,company_size,tools_preferred
0,1,Foster and Sons,Healthcare,Data Analyst,"NumPy, Reinforcement Learning, PyTorch, Scikit...",Mid,Full-time,"Tracybury, AR",92860-109598,2025-08-20,Large,"KDB+, LangChain"
1,2,"Boyd, Myers and Ramirez",Tech,Computer Vision Engineer,"Scikit-learn, CUDA, SQL, Pandas",Senior,Full-time,"Lake Scott, CU",78523-144875,2024-03-22,Large,"FastAPI, KDB+, TensorFlow"
2,3,King Inc,Tech,Quant Researcher,"MLflow, FastAPI, Azure, PyTorch, SQL, GCP",Entry,Full-time,"East Paige, CM",124496-217204,2025-09-18,Large,"BigQuery, PyTorch, Scikit-learn"
3,4,"Cooper, Archer and Lynch",Tech,AI Product Manager,"Scikit-learn, C++, Pandas, LangChain, AWS, R",Mid,Full-time,"Perezview, FI",50908-123743,2024-05-08,Large,"TensorFlow, BigQuery, MLflow"
4,5,Hall LLC,Finance,Data Scientist,"Excel, Keras, SQL, Hugging Face",Senior,Contract,"North Desireeland, NE",98694-135413,2025-02-24,Large,"PyTorch, LangChain"


In [17]:
dataset.shape

(2000, 12)

In [19]:
dataset.isnull().sum()

job_id              0
company_name        0
industry            0
job_title           0
skills_required     0
experience_level    0
employment_type     0
location            0
salary_range_usd    0
posted_date         0
company_size        0
tools_preferred     0
dtype: int64

In [23]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   job_id            2000 non-null   int64 
 1   company_name      2000 non-null   object
 2   industry          2000 non-null   object
 3   job_title         2000 non-null   object
 4   skills_required   2000 non-null   object
 5   experience_level  2000 non-null   object
 6   employment_type   2000 non-null   object
 7   location          2000 non-null   object
 8   salary_range_usd  2000 non-null   object
 9   posted_date       2000 non-null   object
 10  company_size      2000 non-null   object
 11  tools_preferred   2000 non-null   object
dtypes: int64(1), object(11)
memory usage: 187.6+ KB


In [25]:
dataset.describe

<bound method NDFrame.describe of       job_id                   company_name    industry  \
0          1                Foster and Sons  Healthcare   
1          2        Boyd, Myers and Ramirez        Tech   
2          3                       King Inc        Tech   
3          4       Cooper, Archer and Lynch        Tech   
4          5                       Hall LLC     Finance   
...      ...                            ...         ...   
1995    1996       Mueller, Ellis and Clark     Finance   
1996    1997                     Roberts-Yu  Automotive   
1997    1998  Brooks, Williams and Randolph   Education   
1998    1999                Castaneda-Smith   Education   
1999    2000                    Estes Group     Finance   

                     job_title  \
0                 Data Analyst   
1     Computer Vision Engineer   
2             Quant Researcher   
3           AI Product Manager   
4               Data Scientist   
...                        ...   
1995              N

In [28]:
dataset.value_counts("industry")

industry
Automotive    300
Education     294
Retail        293
E-commerce    291
Finance       279
Tech          274
Healthcare    269
Name: count, dtype: int64

In [30]:
dataset.value_counts("job_title")

job_title
Data Analyst                271
NLP Engineer                265
AI Product Manager          258
Quant Researcher            251
ML Engineer                 250
Data Scientist              238
AI Researcher               237
Computer Vision Engineer    230
Name: count, dtype: int64

In [38]:
dataset.duplicated().sum()

0

# Data Preprocessing

In [32]:
dataset.head(10)

,job_id,company_name,industry,job_title,skills_required,experience_level,employment_type,location,salary_range_usd,posted_date,company_size,tools_preferred
0,1,Foster and Sons,Healthcare,Data Analyst,"NumPy, Reinforcement Learning, PyTorch, Scikit...",Mid,Full-time,"Tracybury, AR",92860-109598,2025-08-20,Large,"KDB+, LangChain"
1,2,"Boyd, Myers and Ramirez",Tech,Computer Vision Engineer,"Scikit-learn, CUDA, SQL, Pandas",Senior,Full-time,"Lake Scott, CU",78523-144875,2024-03-22,Large,"FastAPI, KDB+, TensorFlow"
2,3,King Inc,Tech,Quant Researcher,"MLflow, FastAPI, Azure, PyTorch, SQL, GCP",Entry,Full-time,"East Paige, CM",124496-217204,2025-09-18,Large,"BigQuery, PyTorch, Scikit-learn"
3,4,"Cooper, Archer and Lynch",Tech,AI Product Manager,"Scikit-learn, C++, Pandas, LangChain, AWS, R",Mid,Full-time,"Perezview, FI",50908-123743,2024-05-08,Large,"TensorFlow, BigQuery, MLflow"
4,5,Hall LLC,Finance,Data Scientist,"Excel, Keras, SQL, Hugging Face",Senior,Contract,"North Desireeland, NE",98694-135413,2025-02-24,Large,"PyTorch, LangChain"
5,6,Ellis PLC,E-commerce,AI Product Manager,"GCP, Excel, Scikit-learn, MLflow",Senior,Remote,"South Kevin, TZ",92632-180718,2025-08-07,Large,"PyTorch, TensorFlow, FastAPI"
6,7,Matthews-Moses,Automotive,Data Analyst,"Python, Flask, Scikit-learn, GCP",Mid,Full-time,"West Shawn, LR",70575-88594,2024-12-23,Large,"PyTorch, MLflow"
7,8,Mullins Ltd,Education,Data Scientist,"Excel, SQL, Flask",Entry,Internship,"Port Hailey, RU",63032-82144,2024-08-14,Large,BigQuery
8,9,Aguilar PLC,Healthcare,ML Engineer,"Pandas, LangChain, GCP, Azure",Entry,Internship,"Butlermouth, GB",134239-188504,2025-09-15,Large,"Scikit-learn, LangChain, BigQuery"
9,10,Parks LLC,Automotive,Computer Vision Engineer,"Excel, Reinforcement Learning, TensorFlow",Senior,Full-time,"Nicoleshire, BA",79361-165029,2025-08-07,Large,"MLflow, TensorFlow"


In [40]:
# to see types of skills
skills_series = dataset['skills_required'].str.split(', ').explode()
skills_series = skills_series.str.strip() # used for remove extra white spaces
skill_counts = skills_series.value_counts()
print("Skill Counts:")
print(skill_counts)

Skill Counts:
skills_required
TensorFlow                452
Excel                     432
Pandas                    427
FastAPI                   419
NumPy                     416
Reinforcement Learning    414
Azure                     413
Hugging Face              408
SQL                       408
Keras                     406
AWS                       404
Power BI                  404
GCP                       404
Python                    402
LangChain                 401
PyTorch                   401
Scikit-learn              400
Flask                     398
CUDA                      397
R                         393
C++                       390
MLflow                    389
Name: count, dtype: int64


In [57]:
# now list them into an array
unique_skills_array = skills_series.unique()
unique_skills_list = skills_series.unique().tolist()
print(unique_skills_list)

['NumPy', 'Reinforcement Learning', 'PyTorch', 'Scikit-learn', 'GCP', 'FastAPI', 'CUDA', 'SQL', 'Pandas', 'MLflow', 'Azure', 'C++', 'LangChain', 'AWS', 'R', 'Excel', 'Keras', 'Hugging Face', 'Python', 'Flask', 'TensorFlow', 'Power BI']


In [42]:
from sklearn.preprocessing import MultiLabelBinarizer

In [77]:
mlb = MultiLabelBinarizer(classes=unique_skills_list)
list_of_skills_per_row = dataset['skills_required'].apply(lambda x: [skill.strip() for skill in str(x).split(',')])
encoded_skills_matrix = mlb.fit_transform(list_of_skills_per_row)

print(encoded_skills_matrix[:5])

[[1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0]]


In [81]:
dataset.value_counts("experience_level")

experience_level
Entry     702
Mid       668
Senior    630
Name: count, dtype: int64

In [93]:
exp_encoder = OneHotEncoder(sparse_output=False)
encoded_exp_matrix = exp_encoder.fit_transform(dataset[['experience_level']])

for index, row in enumerate(encoded_exp_matrix[:5]):
    clean_string = " ".join(map(str, map(int, row)))
    print(f"{index + 1}. [{clean_string}]")

1. [0 1 0]
2. [0 0 1]
3. [1 0 0]
4. [0 1 0]
5. [0 0 1]


In [97]:
# now encode the output 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(dataset['job_title'])

In [101]:
for index, job in enumerate(le.classes_):
    print(f"{index}: {job}")
print("\nFirst 5 encoded targets (y):", y_encoded[:5])

0: AI Product Manager
1: AI Researcher
2: Computer Vision Engineer
3: Data Analyst
4: Data Scientist
5: ML Engineer
6: NLP Engineer
7: Quant Researcher

First 5 encoded targets (y): [3 2 7 0 4]


In [103]:
dataset.head()

,job_id,company_name,industry,job_title,skills_required,experience_level,employment_type,location,salary_range_usd,posted_date,company_size,tools_preferred
0,1,Foster and Sons,Healthcare,Data Analyst,"NumPy, Reinforcement Learning, PyTorch, Scikit...",Mid,Full-time,"Tracybury, AR",92860-109598,2025-08-20,Large,"KDB+, LangChain"
1,2,"Boyd, Myers and Ramirez",Tech,Computer Vision Engineer,"Scikit-learn, CUDA, SQL, Pandas",Senior,Full-time,"Lake Scott, CU",78523-144875,2024-03-22,Large,"FastAPI, KDB+, TensorFlow"
2,3,King Inc,Tech,Quant Researcher,"MLflow, FastAPI, Azure, PyTorch, SQL, GCP",Entry,Full-time,"East Paige, CM",124496-217204,2025-09-18,Large,"BigQuery, PyTorch, Scikit-learn"
3,4,"Cooper, Archer and Lynch",Tech,AI Product Manager,"Scikit-learn, C++, Pandas, LangChain, AWS, R",Mid,Full-time,"Perezview, FI",50908-123743,2024-05-08,Large,"TensorFlow, BigQuery, MLflow"
4,5,Hall LLC,Finance,Data Scientist,"Excel, Keras, SQL, Hugging Face",Senior,Contract,"North Desireeland, NE",98694-135413,2025-02-24,Large,"PyTorch, LangChain"
